### ISSUE TITLE
Feature Request: Planet Improvement Todo List

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [Just-a-Unity-Dev/dimineral#13]
## Main
- [x] Basic stars/planets
- [ ] Buying fuel
- [ ] Mining
- [ ] Hiring crew

## Integrations
- [ ] Integrate with cargo
- [ ] Integrate with diplomacy
- [ ] Integrate with PvP
- [ ] Integrate with AI
